name: Check Github Pages Gem Version and Open New Issue on Change

on: workflow_dispatch

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Daniel Ridge repo
        uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Fetch release version
        run: |
          curl -sL https://pages.github.com/versions.json | \
          jq -r '."github-pages"' > release-versions/github-pages-gem.txt
          
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
        
      - name: Open new issue
        if: steps.git-check.outputs.modified == 'true'
        run: gh issue create 
            --repo github.com/ericvennemeyer/HFLA-Daniel-Ridge-Bot-Test 
            --title "Github Pages Gem Has a New Version" 
            --body "Please refer to ghpages-docker README or wiki for instructions on how to update."
        env:
            GH_TOKEN: ${{ secrets.Daniel_Ridge_PAT }}
  
#   open_issue:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out THIS repo
#         uses: actions/checkout@v3
        
#       - name: Open issue in DIFFERENT repo
#         run: gh issue create 
#             --repo github.com/ericvennemeyer/HFLA-Daniel-Ridge-Bot-Test 
#             --title "I found a bug" 
#             --body "Nothing works"
#         env:
#             GH_TOKEN: ${{ secrets.Daniel_Ridge_PAT }}
