name: Check Github Pages Gem Version and Open New Issue on Change

on: workflow_dispatch

jobs:
  get-github-pages-gem-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Daniel Ridge repo
        uses: actions/checkout@v3
        
      - name: Set ENV variables for current ghpages-docker version number
        run: echo "CURRENT_VERSION=$(cat release-versions/github-pages-gem.txt)" >> $GITHUB_ENV
        
      - name: Set ENV variables for current GitHub Pages dependency version number 
        run: echo "NEW_VERSION=$(curl -sL https://pages.github.com/versions.json | jq -r '."github-pages"')" >> $GITHUB_ENV

      - name: Fetch release version
        run: |
          ${{ env.NEW_VERSION }} > release-versions/github-pages-gem.txt
          
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
        
      - name: Open new issue
        if: steps.git-check.outputs.modified == 'true'
        run: gh issue create 
            --repo github.com/ericvennemeyer/HFLA-Daniel-Ridge-Bot-Test 
            --title "GHPAGES-DOCKER needs to be updated" 
            --body "GitHub Pages is now using v${{ env.NEW_VERSION }} of the GitHub Pages Gem. You are using v${{ env.CURRENT_VERSION }}. Please refer to ghpages-docker README or Wiki for instructions on how to update."
        env:
            GH_TOKEN: ${{ secrets.Daniel_Ridge_PAT }}
            
  get-ruby-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Daniel Ridge repo
        uses: actions/checkout@v3

      - name: Fetch release version
        run: |
          curl -sL https://pages.github.com/versions.json | \
          jq -r '."ruby"' > release-versions/ruby.txt

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Open new issue
        if: steps.git-check.outputs.modified == 'true'
        run: gh issue create 
            --repo github.com/ericvennemeyer/HFLA-Daniel-Ridge-Bot-Test 
            --title "GHPAGES-DOCKER needs to be updated" 
            --body "GitHub Pages is now using a newer version of Ruby. Please refer to ghpages-docker README or Wiki for instructions on how to update."
        env:
            GH_TOKEN: ${{ secrets.Daniel_Ridge_PAT }}
  
#   open_issue:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out THIS repo
#         uses: actions/checkout@v3
        
#       - name: Open issue in DIFFERENT repo
#         run: gh issue create 
#             --repo github.com/ericvennemeyer/HFLA-Daniel-Ridge-Bot-Test 
#             --title "I found a bug" 
#             --body "Nothing works"
#         env:
#             GH_TOKEN: ${{ secrets.Daniel_Ridge_PAT }}
